spring.application.name=springboot-demo2
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management?serverTimezone=GMT&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=mimashi625
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis-plus.mapper-locations=classpath*:mappers/*.xml
